
import { VerticalBox, Button, ListView, Palette, HorizontalBox } from "std-widgets.slint";

export global Directories {
    in-out property <[string]> log-files: [
        "2023-10-24 20:25:43.283, root, INFO, DynamicAcquisition, acqpatterns.py:212, DynamicAcquisition acquiring C14486GA 822OI006 at 960000 us",
        "2023-10-24 20:25:44.275, root, INFO, DynamicAcquisition, acqpatterns.py:256, DynamicAcquisition: Begin optimization of integration time.",
        "2023-10-24 15:48:59.288, root, INFO, DynamicAcquisition, acqpatterns.py:423, Integration Time Fit (us), max value, maxIdx: 120000, 38136.0, 889.622",
        "2023-10-24 15:48:59.441, root, INFO, DynamicAcquisition, acqpatterns.py:444, Integration Time Best (us): 120000",
        "2023-10-24 15:49:01.623, root, INFO, DynamicAcquisition, acqpatterns.py:423, Integration Time Fit (us), max value, maxIdx: 960000, 43270.0, 153.605",
        "2023-10-24 15:49:02.621, root, INFO, DynamicAcquisition, acqpatterns.py:444, Integration Time Best (us): 960000",
    ];

    callback refresh();
}

export component MatauriBayLogs {
    VerticalBox {
        ListView {
            for data in Directories.log-files: HorizontalBox {
                padding: 2px;
                Rectangle {
                    height: 20px;
                    background: Palette.background;
                    border-color: Palette.border;
                    border-width: 0.5px;
                    Text {
                        x: 7px;
                        font-size: 14px;
                        text: data;
                        wrap: TextWrap.word-wrap;
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            Button {
                text: "Refresh";
                clicked => {
                    Directories.refresh();
                }
            }
        }
    }
}
