import { Button, VerticalBox, StandardListView, ListView, TabWidget, Palette, AboutSlint, StandardButton } from "std-widgets.slint";
import { MatauriBayLogs, Directories } from "pages/matauri-bay.slint";
import { AboutPage } from "pages/about.slint";

export { Directories }

export component AppWindow inherits Window {
    preferred-width: 900px;
    preferred-height: 500px;
    icon: @image-url("../assets/log-16x16.png");
    title: "Log Viewer";

    VerticalBox {
        tabs := TabWidget {
            max-height: 30px;
            Tab {
                title: "Matauri Bay";
            }

            Tab {
                title: "Spectro Server";
            }

            Tab {
                title: "About";
            }
        }

        if tabs.current-index == 0: MatauriBayLogs { }

        if tabs.current-index == 1: Text {
            vertical-alignment: center;
            font-size: 20px;
            horizontal-alignment: center;
            text: "Not yet implemented";
        }
        if tabs.current-index == 2: AboutPage { }
    }
}
