export global LabPalette {
    out property <color> dark-blue: #00313c;
    out property <color> teal: #007681;
    out property <color> light-gray: #b1b3b3;
    out property <color> dark-gray: #63666a;

    out property <color> orange: #D57800;
    out property <color> green: #74AA50;
    out property <color> yellow: #EAAA00;
    out property <color> red: #E04E39;
    out property <color> dusty-rose: #E8927C;
    out property <color> olive-green: #AC9F3C;
    out property <color> blue: #4298B5;
    out property <color> purple: #5D4777;
    out property <color> burgundy: #672E45;

}